# Generated by Django 3.2.5 on 2021-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='clientlastname', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='clientname', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name',
            field=models.CharField(default='workerlastname', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.CharField(default='workername', max_length=255),
        ),
    ]
